# Generated by Django 2.0 on 2019-05-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
